
package de.kundenverwaltung.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "KundenService", targetNamespace = "http://webservice.kundenverwaltung.de/", wsdlLocation = "file:/C:/java/workspace/KundenverwaltungWs/META-INF/wsdl/KundenService.wsdl")
public class KundenService
    extends Service
{

    private final static URL KUNDENSERVICE_WSDL_LOCATION;
    private final static WebServiceException KUNDENSERVICE_EXCEPTION;
    private final static QName KUNDENSERVICE_QNAME = new QName("http://webservice.kundenverwaltung.de/", "KundenService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/java/workspace/KundenverwaltungWs/META-INF/wsdl/KundenService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KUNDENSERVICE_WSDL_LOCATION = url;
        KUNDENSERVICE_EXCEPTION = e;
    }

    public KundenService() {
        super(__getWsdlLocation(), KUNDENSERVICE_QNAME);
    }

    public KundenService(WebServiceFeature... features) {
        super(__getWsdlLocation(), KUNDENSERVICE_QNAME, features);
    }

    public KundenService(URL wsdlLocation) {
        super(wsdlLocation, KUNDENSERVICE_QNAME);
    }

    public KundenService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KUNDENSERVICE_QNAME, features);
    }

    public KundenService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KundenService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns KundenSEI
     */
    @WebEndpoint(name = "KundenServicePort")
    public KundenSEI getKundenServicePort() {
        return super.getPort(new QName("http://webservice.kundenverwaltung.de/", "KundenServicePort"), KundenSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KundenSEI
     */
    @WebEndpoint(name = "KundenServicePort")
    public KundenSEI getKundenServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.kundenverwaltung.de/", "KundenServicePort"), KundenSEI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KUNDENSERVICE_EXCEPTION!= null) {
            throw KUNDENSERVICE_EXCEPTION;
        }
        return KUNDENSERVICE_WSDL_LOCATION;
    }

}
