
package de.kiltz.seminar.ejb3.ws.kunde;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "KundenClientService", targetNamespace = "http://kunde.ws.ejb3.seminar.kiltz.de/", wsdlLocation = "file:/C:/java/workspace/11-WS/wsdl/KundenSIB.wsdl")
public class KundenClientService
    extends Service
{

    private final static URL KUNDENCLIENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException KUNDENCLIENTSERVICE_EXCEPTION;
    private final static QName KUNDENCLIENTSERVICE_QNAME = new QName("http://kunde.ws.ejb3.seminar.kiltz.de/", "KundenClientService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/java/workspace/11-WS/wsdl/KundenSIB.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KUNDENCLIENTSERVICE_WSDL_LOCATION = url;
        KUNDENCLIENTSERVICE_EXCEPTION = e;
    }

    public KundenClientService() {
        super(__getWsdlLocation(), KUNDENCLIENTSERVICE_QNAME);
    }

    public KundenClientService(WebServiceFeature... features) {
        super(__getWsdlLocation(), KUNDENCLIENTSERVICE_QNAME, features);
    }

    public KundenClientService(URL wsdlLocation) {
        super(wsdlLocation, KUNDENCLIENTSERVICE_QNAME);
    }

    public KundenClientService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KUNDENCLIENTSERVICE_QNAME, features);
    }

    public KundenClientService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KundenClientService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns KundenWebService
     */
    @WebEndpoint(name = "KundenWebService")
    public KundenWebService getKundenWebService() {
        return super.getPort(new QName("http://kunde.ws.ejb3.seminar.kiltz.de/", "KundenWebService"), KundenWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KundenWebService
     */
    @WebEndpoint(name = "KundenWebService")
    public KundenWebService getKundenWebService(WebServiceFeature... features) {
        return super.getPort(new QName("http://kunde.ws.ejb3.seminar.kiltz.de/", "KundenWebService"), KundenWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KUNDENCLIENTSERVICE_EXCEPTION!= null) {
            throw KUNDENCLIENTSERVICE_EXCEPTION;
        }
        return KUNDENCLIENTSERVICE_WSDL_LOCATION;
    }

}
