
package de.webservice.publisher;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InfoserviceGen", targetNamespace = "http://publisher.webservice.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InfoserviceGen {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTime", targetNamespace = "http://publisher.webservice.de/", className = "de.webservice.publisher.GetTime")
    @ResponseWrapper(localName = "getTimeResponse", targetNamespace = "http://publisher.webservice.de/", className = "de.webservice.publisher.GetTimeResponse")
    @Action(input = "http://publisher.webservice.de/InfoserviceGen/getTimeRequest", output = "http://publisher.webservice.de/InfoserviceGen/getTimeResponse")
    public String getTime();

    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFreeMemory", targetNamespace = "http://publisher.webservice.de/", className = "de.webservice.publisher.GetFreeMemory")
    @ResponseWrapper(localName = "getFreeMemoryResponse", targetNamespace = "http://publisher.webservice.de/", className = "de.webservice.publisher.GetFreeMemoryResponse")
    @Action(input = "http://publisher.webservice.de/InfoserviceGen/getFreeMemoryRequest", output = "http://publisher.webservice.de/InfoserviceGen/getFreeMemoryResponse")
    public long getFreeMemory();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://publisher.webservice.de/", className = "de.webservice.publisher.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://publisher.webservice.de/", className = "de.webservice.publisher.GetUserResponse")
    @Action(input = "http://publisher.webservice.de/InfoserviceGen/getUserRequest", output = "http://publisher.webservice.de/InfoserviceGen/getUserResponse")
    public String getUser();

}
